### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [JaneJeon/objection-hashid#46]
Similar to my proposal left on your [objection-authorize repo](https://github.com/JaneJeon/objection-authorize/issues/1), would you be willing to let me add a type declaration file to this project?

**Comment by JaneJeon** [comment]
Same as in the other repo, please, I'd love your help!

This library is probably a _lot_ simpler than the other one (not just in terms of what it does, but also in terms of the actual `.d.ts` file).

Please, feel free to make a PR!

**Comment by simo-eskalera** [comment]
Has this landed? It would be a great addition!

**Comment by geopic** [comment]
Not yet @simo-eskalera

**Comment by JaneJeon** [comment]
For now, we'll leave this issue alone...
