### ISSUE TITLE
Option to skip hashing per model

### ISSUE THREAD

**Issue by simoami** [JaneJeon/objection-hashid#53]
It would be great to have the option to flag some models for skipping, so that this plugin can be deployed to large apps. One might want to target a subset of the models and extend to other models over time.

**Comment by JaneJeon** [comment]
Hi, we actually already have this feature.

As outlined in the README:
```
To configure which field the hashid is written to during serialization, set the static hashIdField property.
By default, it's id, but you can change it to any string (e.g. hashid), or, you can set it to a falsey value to disable writing the hashid to the final object, meaning you can only access the hashid before it's serialized.
```

So basically set `hashIdField` to `false` or any falsey value for any model you want to skip hashing on!

**Comment by simoami** [comment]
Thanks @JaneJeon. In this case, you may want to review the typing for the hasIdField in #46 , which only expects a string. If false is expected then the typing would need to be corrected:
```
static get hashIdField(): string | boolean;
```

**Comment by JaneJeon** [comment]
@simoami the typing is a WIP, but thanks for letting me know. And yeah, I'd say definitely just slap on a `false` in `hashIdField` - the typing doesn't matter as much as the value being falsey

@geopic some additional typing changes requested, thanks
